### ISSUE TITLE
[Help wanted] How to use OMNeT federates? 

### ISSUE THREAD

**Issue by tnowak1502** [usnistgov/ucef-core#19]
I am using the 1.0.0BETA virtual machine.

Sorry if this is not the right repository to add this issue to.

I followed the tutorial for the PingPong Java Federation, which worked fine, but I want to use an OMNeT++ federate to simulate a network in my federation and I don't understand how to do that. The .zip files generated by WebGME do contain folders for the OMNeT federate, but those folders don't contain any skeleton code, so I'm not sure how I'm supposed to create the OMNeT federate and how it should be integrated with the federation, as I want multiple federates to communicate through the network simulated by the OMNeT federate. 

I noticed that there are examples containing OMNeT federates in the cpswt-cpp folder, but I don't know how to run them.

I would be very grateful for any help with this issue.

**Comment by tpr1** [comment]
The OMNeT++ federate is no longer supported; it's implementation was not kept up-to-date with the rest of the code base. At the moment, there is no network simulator working in UCEF. We plan to re-implement a network simulator by late next year; so it will be a while before it's supported again.

Sorry I couldn't be of help!

**Comment by tnowak1502** [comment]
No problem, thank you for your reply regardless. Do Matlab federates work currently? I noticed that they are not listed in the "Include" parameter of the federates exporter, and trying to run it when a Matlab federate is present leads to errors ('TypeError: self [(visit_" + nodeType)] is not a function').

**Comment by tpr1** [comment]
The Simulink federate does not work, and there is no current plan to support it. A lot of the components in the parts browser are outdated; we've until recently been unable to remove the unsupported federate types due to an issue with how the modeling language was developed.

The Java, C++, and GridLAB-D federates are stable. We have an EnergyPlus federate in reasonable shape, but it doesn't appear in WebGME and requires some support to use. There are also TRNSYS and LabVIEW federates that are a bit difficult to use, both of which appear in (the latest version of) WebGME and code generate as intended. All other simulators should be considered unsupported.

**Comment by tnowak1502** [comment]
Alright, thank you very much!
